INSERT into House Values ('Avalon','Kilgo');
INSERT into House Values ('Banham', 'Edens');
INSERT into House Values ('Bastille' ,'Edens');
INSERT into House Values ('Bel Air', 'Edens');
INSERT into House Values ('Blue Ridge', 'Keohane');
INSERT into House Values ('Farquaad' ,'Edens');
INSERT into House Values ('Gates', 'Crowell');
INSERT into House Values ('Griffin', 'Crowell');
INSERT into House Values ('Hart', 'Crowell');
INSERT into House Values ('House 3B', 'Edens');
INSERT into House Values ('Hun', 'Few');
INSERT into House Values ('Khaya', 'Edens');
INSERT into House Values ('Lumos', 'Craven');
INSERT into House Values ('Magnolia Commons', 'Crowell');
INSERT into House Values ('Marquis', 'Kilgo');
INSERT into House Values ('Montauk', 'Few');
INSERT into House Values ('Mt. Olympus' ,'Hollows');
INSERT into House Values ('Narnia', 'Hollows');
INSERT into House Values ('Ox' ,'Keohane');
INSERT into House Values ('Powerhouse' ,'Craven');
INSERT into House Values ('Pride Rock', 'Few');
INSERT into House Values ('Rabbit Hole' ,'Hollows');
INSERT into House Values ('Sherwood', 'Craven');
INSERT into House Values ('Shire', 'Keohane');
INSERT into House Values ('Sierra', '300 Swift');
INSERT into House Values ('Skylar', 'Hollows');
INSERT into House Values ('Stark' ,'Wannamaker');
INSERT into House Values ('Stonehenge' ,'Kilgo');
INSERT into House Values ('Styron' ,'Few');
INSERT into House Values ('Tortuga' ,'Hollows');
INSERT into House Values ('Windsor', 'Keohane');
INSERT INTO Major VALUES ('African and African American Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Air Force ROTC','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Army ROTC','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Art, Art History and Visual Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Arts of the Moving Image','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Asian and Middle Eastern Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Biology','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Chemistry','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Classical Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Computer Science','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Cultural Anthropology','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Dance','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Economics','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Education','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('English','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Evolutionary Anthropology','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Gender, Sexuality and Feminist Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Germanic Languages and Literature','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Health, Wellness and Physical Education','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('History','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('International Comparative Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Linguistics','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Literature','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Mathematics','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('MFA in Experimental and Documentary Arts','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Music','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Navy ROTC','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Philosophy','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Physics','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Political Science','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Psychology','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Neuroscience','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Religious Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Romance Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Slavic and Eurasian Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Sociology','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Statistical Science','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Theater Studies','Trinity College of Arts and Sciences');
INSERT INTO Major VALUES ('Biomedical Engineering','Pratt School of Engineering');
INSERT INTO Major VALUES ('Civil Engineering','Pratt School of Engineering');
INSERT INTO Major VALUES ('Environmental Engineering','Pratt School of Engineering');
INSERT INTO Major VALUES ('Electrical and Computer Engineering','Pratt School of Engineering');
INSERT INTO Major VALUES ('Mechanical Engineering','Pratt School of Engineering');
INSERT INTO Major VALUES ('Energy Engineering','Pratt School of Engineering');
